name: Update Tracks JSON

on:
  push:
    paths:
      - 'audio/**'

jobs:
  update-tracks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Generate tracks.json
        run: |
          node .github/scripts/generate-tracks.js
          
      - name: Commit updated tracks.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update tracks.json
          file_pattern: tracks.json
